# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: adc99e6953b323db5082547acd35ea1fa84bb5c4c7001fd4ca6449117bf0b6a1092d9f2bdafb43b3d81e73eec1434c792eb212df76ebd775ec9c72617c0e1100

test:
  secret_key_base: b6271d2cb3e2c8a24a654c1ebded748afb0c185d39985223141943433321d753b12ea116b38d23f0f0bc8dc724c08141047f7931f5ec613e41567f345a7e46fe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
